---
title: "Individuals Info"
author: "Joffrey JOUMAA"
date: "`r invisible(Sys.setlocale(locale = 'C')); format(Sys.Date(), format = '%B %d, %Y')`"
output:
  bookdown::html_document2:
    css: cosmo_custom.css
    number_sections: yes
    code_folding: show
    df_print: default
    fig_caption: yes
    code_download: yes
vignette: >
  %\VignetteIndexEntry{Individuals Info}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  fig.align = "center",
  out.width = "100%",
  message = FALSE,
  warning = FALSE,
  cache.lazy = FALSE,
  optipng = "-o7 -quiet",
  pngquant = "--speed=1"
)

# library
library(data.table)
library(ggplot2)
library(ggnewscale)
library(ggplot2)
library(magrittr)
library(ggOceanMaps)
library(ggOceanMapsData)
library(maps)
library(cowplot)
library(scales)
library(sf)
library(weanlingNES)
library(ggpubr)
library(gridExtra)

# remove some warnings
suppressWarnings(library(ggplot2))
```

```{r echo=FALSE}
# read the processed data
# data_2018_filter <- readRDS("tmp/data_2018_filter.rds")
library(weanlingNES)
data("data_nes")
data("data_ses")
data_2018_nes <- rbindlist(data_nes$year_2018)
data_2014_ses <- rbindlist(data_ses$year_2014)
```

## Northern Elephant Seals {.tabset .tabset-fade .tabset-pills}

```{r plot_ind_nes, results='asis', cache=TRUE, echo=FALSE, fig.asp=1.7}
for (i in data_2018_nes[!is.na(lat), unique(.id)]) {
  cat("###", i, "{.unlisted .unnumbered} \n")
  print(plot_ind(data_2018_nes[.id == i,]))
  cat("\n \n")
}
```

## Southern Elephant Seals {.tabset .tabset-fade .tabset-pills}

```{r plot_ind_ses, results='asis', cache=TRUE, echo=FALSE, fig.asp=1.7}
for (i in data_2014_ses[!is.na(lat), unique(.id)]) {
  cat("###", i, "{.unlisted .unnumbered} \n")
  print(plot_ind(data_2014_ses[.id == i,]))
  cat("\n \n")
}
```

## {.unlisted .unnumbered}
